version: "3"

services:
  back_app:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - "${PORT:-8081}:80"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    command: npm run start-only
    environment:
      - BIKES=${BIKES:-development}
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT:-27017}:27017
volumes:
  mongodata:
